export const LOG_WORKOUT_START = 'LOG_WORKOUT_START';
export const LOG_WORKOUT_SUCCESS = 'LOG_WORKOUT_SUCCESS';
export const LOG_WORKOUT_FAIL = 'LOG_WORKOUT_FAIL';
export const LOG_WORKOUT_INIT = 'LOG_WORKOUT_INIT';

export const FETCH_WORKOUTS_START = 'FETCH_WORKOUTS_START';
export const FETCH_WORKOUTS_SUCCESS = 'FETCH_WORKOUTS_SUCCESS';
export const FETCH_WORKOUTS_FAIL = 'FETCH_WORKOUTS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';